# Generated by Django 4.2.2 on 2023-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_categoriaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgProducto',
            field=models.CharField(default='404.png', max_length=50, verbose_name='Dirección de la imagen del producto desde static/core/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto'),
        ),
    ]
