# Generated by Django 4.2.2 on 2023-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_imgproducto_alter_producto_idproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idCategoria',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombreCategoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaProducto',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imgProducto',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precio',
        ),
    ]
