# Generated by Django 4.2.2 on 2023-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción corta del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='texto',
            field=models.TextField(null=True, verbose_name='Descripciión larga del produucto'),
        ),
    ]
