# Generated by Django 4.2.2 on 2023-06-19 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_servicio_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dvrut',
            field=models.CharField(default='F', max_length=1, verbose_name='Dígito Verificador del RUT del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numrut',
            field=models.IntegerField(default=99999999, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Número del RUT del cliente'),
            preserve_default=False,
        ),
    ]
