# Generated by Django 4.2.2 on 2023-06-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_dvrut_cliente_numrut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularioContacto',
            new_name='ContactoServicio',
        ),
        migrations.AlterModelTable(
            name='contactoservicio',
            table='core_cliente_servicio',
        ),
    ]
