# Generated by Django 4.2.2 on 2023-07-02 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_rename_formulariocontacto_contactoservicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de orden')),
                ('estado_pago', models.BooleanField(default=False, verbose_name='Estado de pago de la orden')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
        ),
        migrations.AlterModelOptions(
            name='contactoservicio',
            options={'verbose_name': 'cliente servicio', 'verbose_name_plural': 'cliente servicio'},
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de relación producto-orden')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'producto-orden',
                'verbose_name_plural': 'productos-ordenes',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(through='core.ProductoOrden', to='core.producto', verbose_name='Productos de la orden'),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id del usuario'),
        ),
    ]
