# Generated by Django 4.2.2 on 2023-07-02 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_orden_alter_contactoservicio_options_productoorden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id del usuario'),
        ),
    ]
