# Generated by Django 4.2.2 on 2023-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_orden_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoorden',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de productos'),
            preserve_default=False,
        ),
    ]
